name: Weekly CI

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  spec:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        crystal: [1.9.0, 1.8.0, latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec --error-trace
        # - name: Check formatting
        #   run: crystal tool format --check
